version: "3.8"
services:
  server:
    build: .
    command: npm run watch
    container_name: server
    ports:
      - "${HTTP_PORT}:8000"
    volumes:
      - ./:/var/www/
      - /var/www/vendor
    depends_on:
      - pgsql
    links:
      - pgsql
  pgsql:
    image: pgsql
    container_name: pgsql
    command: --default-authentication-plugin=pgsql_native_password
    restart: always
    environment:
      pgsql_DATABASE: ${DB_DATABASE}
      pgsql_USER: ${DB_USERNAME}
      pgsql_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PGSQL_PORT}:5432
    volumes:
      - ./pgsql/init.sql:/data/application/init.sql
      - pgsql_data:/var/lib/pgsql
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    container_name: client
    volumes:
      - ./:/var/www/
      - /var/www/node_modules
    depends_on:
      - "server"
volumes:
  pgsql_data: